"""initial_schema

Revision ID: 26998facdffe
Revises: 
Create Date: 2026-02-09 15:51:03.394074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26998facdffe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baselines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='基线名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='基线描述'),
    sa.Column('source_heat_id', sa.String(length=36), nullable=False, comment='来源炉次ID'),
    sa.Column('power_curve', sa.Text(), nullable=False, comment='功率曲线JSON'),
    sa.Column('voltage_curve', sa.Text(), nullable=False, comment='电压曲线JSON'),
    sa.Column('temperature', sa.Float(), nullable=True, comment='出汤温度(°C)'),
    sa.Column('tolerance_percent', sa.Float(), nullable=False, comment='容许误差百分比'),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'DISABLED', name='baselinestatus'), nullable=False, comment='状态'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False, comment='配置键名'),
    sa.Column('value', sa.Text(), nullable=False, comment='配置值JSON'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='配置描述'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('heats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('heat_no', sa.String(length=50), nullable=False, comment='炉次编号'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=False, comment='结束时间'),
    sa.Column('power_curve', sa.Text(), nullable=False, comment='功率曲线JSON'),
    sa.Column('voltage_curve', sa.Text(), nullable=False, comment='电压曲线JSON'),
    sa.Column('temperature', sa.Float(), nullable=True, comment='出汤温度(°C)'),
    sa.Column('baseline_id', sa.String(length=36), nullable=True, comment='对比基线ID'),
    sa.Column('deviation_percent', sa.Float(), nullable=True, comment='最大偏差百分比'),
    sa.Column('avg_deviation_percent', sa.Float(), nullable=True, comment='平均偏差百分比'),
    sa.Column('deviation_details', sa.Text(), nullable=True, comment='偏差区间详情JSON'),
    sa.Column('status', sa.Enum('NORMAL', 'ABNORMAL', 'PENDING', name='heatstatus'), nullable=False, comment='偏差状态'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['baseline_id'], ['baselines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('heat_no')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_no', sa.String(length=50), nullable=False, comment='任务编号'),
    sa.Column('heat_id', sa.String(length=36), nullable=False, comment='关联炉次ID'),
    sa.Column('deviation_percent', sa.Float(), nullable=False, comment='偏差百分比'),
    sa.Column('deviation_snapshot', sa.Text(), nullable=False, comment='偏差详情快照JSON'),
    sa.Column('cause_analysis', sa.Text(), nullable=True, comment='原因分析'),
    sa.Column('improvement', sa.Text(), nullable=True, comment='改善方法'),
    sa.Column('prevention', sa.Text(), nullable=True, comment='预防对策'),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus'), nullable=False, comment='任务状态'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.ForeignKeyConstraint(['heat_id'], ['heats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('heats')
    op.drop_table('settings')
    op.drop_table('baselines')
    # ### end Alembic commands ###
