"""数据模式模块

导出所有 Pydantic 模式供其他模块使用。
"""

from .baseline import (
    BaselineCreate,
    BaselineListResponse,
    BaselinePreviewJobResponse,
    BaselinePreviewResponse,
    BaselineResponse,
    BaselineSummary,
    BaselineUpdate,
    BaselineWithCurve,
    CurveData,
)
from .common import (
    CurvePoint,
    DateRangeParams,
    ErrorResponse,
    MessageResponse,
    PaginatedResponse,
    PaginationParams,
)
from .dashboard import (
    DashboardStats,
    RealtimeCurveData,
    RecentHeat,
    RecentHeatsResponse,
)
from .heat import (
    BaselineCompareItem,
    CuttingTimelineEvent,
    CuttingTimelineResponse,
    DeviationRange,
    HeatAnalyzeRequest,
    HeatAnalyzeResponse,
    HeatCompareResponse,
    HeatListResponse,
    HeatResponse,
    HeatResumeCuttingRequest,
    HeatUpdate,
    HeatWithCurve,
    MetricCompareSeries,
)
from .setting import (
    BaselineLengthScopeSettingRequest,
    ChannelRoleBindingCollectionResponse,
    ChannelRoleBindingItem,
    ChannelRoleBindingUpdateRequest,
    CuttingSettingRequest,
    EDCConnectionRequest,
    HostChannelCollectionResponse,
    HostChannelCollectionUpdateRequest,
    HostChannelItem,
    HostBootstrapResponse,
    HostConnectivityMeta,
    HostConnectivityStatusResponse,
    HostConnectivityStatusUpdateRequest,
    HostRuntimeSyncRequest,
    HostRuntimeSyncResponse,
    HostSourceConfig,
    ReportSettingRequest,
    RuntimeActiveBaselineSummary,
    RuntimeChannelRolesSummary,
    RuntimeEDCConnectionSummary,
    RuntimeFlagsSummary,
    RuntimePipelinesSummary,
    RuntimePipelineStatus,
    RuntimeStatusResponse,
    SettingItem,
    SettingsResponse,
    SettingsUpdateRequest,
    ToleranceSettingRequest,
)
from .source_switch import SourceSwitchRequest, SourceSwitchResponse
from .task import (
    TaskCompleteRequest,
    TaskCreate,
    TaskDetailResponse,
    TaskListResponse,
    TaskResponse,
    TaskUpdate,
    TaskWithHeat,
)

__all__ = [
    # Common
    "CurvePoint",
    "PaginationParams",
    "PaginatedResponse",
    "DateRangeParams",
    "MessageResponse",
    "ErrorResponse",
    # Baseline
    "BaselineCreate",
    "BaselineUpdate",
    "BaselineResponse",
    "BaselineWithCurve",
    "BaselineListResponse",
    "BaselinePreviewJobResponse",
    "BaselinePreviewResponse",
    "BaselineSummary",
    "CurveData",
    # Heat
    "DeviationRange",
    "MetricCompareSeries",
    "BaselineCompareItem",
    "CuttingTimelineEvent",
    "CuttingTimelineResponse",
    "HeatResponse",
    "HeatWithCurve",
    "HeatCompareResponse",
    "HeatListResponse",
    "HeatResumeCuttingRequest",
    "HeatAnalyzeRequest",
    "HeatAnalyzeResponse",
    "HeatUpdate",
    # Task
    "TaskCreate",
    "TaskUpdate",
    "TaskResponse",
    "TaskWithHeat",
    "TaskListResponse",
    "TaskDetailResponse",
    "TaskCompleteRequest",
    # Setting
    "SettingItem",
    "SettingsResponse",
    "ChannelRoleBindingItem",
    "ChannelRoleBindingCollectionResponse",
    "ChannelRoleBindingUpdateRequest",
    "HostChannelItem",
    "HostChannelCollectionResponse",
    "HostChannelCollectionUpdateRequest",
    "HostBootstrapResponse",
    "HostConnectivityMeta",
    "HostConnectivityStatusResponse",
    "HostConnectivityStatusUpdateRequest",
    "HostRuntimeSyncRequest",
    "HostRuntimeSyncResponse",
    "HostSourceConfig",
    "RuntimeEDCConnectionSummary",
    "RuntimeActiveBaselineSummary",
    "RuntimeChannelRolesSummary",
    "RuntimeFlagsSummary",
    "RuntimePipelineStatus",
    "RuntimePipelinesSummary",
    "RuntimeStatusResponse",
    "SettingsUpdateRequest",
    "ToleranceSettingRequest",
    "SourceSwitchRequest",
    "SourceSwitchResponse",
    "BaselineLengthScopeSettingRequest",
    "CuttingSettingRequest",
    "EDCConnectionRequest",
    "ReportSettingRequest",
    # Dashboard
    "DashboardStats",
    "RealtimeCurveData",
    "RecentHeat",
    "RecentHeatsResponse",
]
